name: HCA_TEST
favicon: null
layout_spectrum: 0.7351
typography_spectrum: 0.8509678870905191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#36251b'
    - '#4e4a24'
    - '#857c7d'
    - '#c3bfbf'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
